== Ffdb

ifdef::env-github[]
image:https://img.shields.io/gem/v/ffdb.svg[
	Gem Version, link="https://rubygems.org/gems/ffdb"]
image:https://img.shields.io/travis/riboseinc/ffdb/master.svg[
	Build Status, link="https://travis-ci.org/riboseinc/ffdb/branches"]
image:https://img.shields.io/codecov/c/github/riboseinc/ffdb.svg[
	Test Coverage, link="https://codecov.io/gh/riboseinc/ffdb"]
// image:https://img.shields.io/codeclimate/coverage/riboseinc/ffdb.svg[
//	Test Coverage, link="https://codeclimate.com/github/riboseinc/ffdb"]
image:https://img.shields.io/codeclimate/maintainability/riboseinc/ffdb.svg[
	Code Climate, link="https://codeclimate.com/github/riboseinc/ffdb"]
endif::[]

ifdef::env-gitlab[]
image:https://img.shields.io/gem/v/ffdb.svg[
	Gem Version, link="https://rubygems.org/gems/ffdb"]
image:https://img.shields.io/gitlab/pipeline/riboseinc/ffdb.svg[
	GitLab pipeline, link="https://gitlab.com/riboseinc/ffdb/pipelines"]
endif::[]

Welcome to your new gem! In this directory, you’ll find the files you need to be
able to package up your Ruby library into a gem. Put your Ruby code in the file
`lib/ffdb`. To experiment with that code, run `bin/console` for an interactive
prompt.

TODO: Delete this and the text above, and describe your gem

=== Installation

Add this line to your application’s Gemfile:

[source,ruby]
----
gem 'ffdb'
----

And then execute:

....
$ bundle
....

Or install it yourself as:

....
$ gem install ffdb
....

=== Usage

TODO: Write usage instructions here

=== Development

After checking out the repo, run `bin/setup` to install dependencies. Then, run
`rake spec` to run the tests. You can also run `bin/console` for an interactive
prompt that will allow you to experiment.

To install this gem onto your local machine, run `bundle exec rake install`. To
release a new version, update the version number in `version.rb`, and then run
`bundle exec rake release`, which will create a git tag for the version, push
git commits and tags, and push the `.gem` file to
https://rubygems.org[rubygems.org].

=== Contributing

Bug reports and pull requests are welcome on GitHub at
https://github.com/riboseinc/ffdb. This project is intended to be a safe,
welcoming space for collaboration, and contributors are expected to adhere to
the http://contributor-covenant.org[Contributor Covenant] code of conduct.

=== License

The gem is available as open source under the terms of the
https://opensource.org/licenses/MIT[MIT License].

=== Code of Conduct

Everyone interacting in the Ffdb project’s codebases, issue trackers, chat rooms
and mailing lists is expected to follow the
https://github.com/riboseinc/ffdb/blob/master/CODE_OF_CONDUCT.adoc[code of
conduct].
